import Head from 'next/head';
import { useState } from 'react';
import Project from '../components/projects';
import About from '../components/about';
import Resume from '../components/resume';
import Skills from '../components/skills';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Izhan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="leading-normal tracking-normal mx-auto w-10/12 text-black gradient">
        <section id="hero">
          <div className="py-40">
            <div className="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
              <div className="flex flex-col w-full justify-center items-center text-center">
                <h1 className="my-4 text-5xl md:text-6xl font-bold leading-tight text-center ">
                  Mohammed Izhan
                </h1>
                <p className="leading-normal text-2xl mb-8 text-center ">
                  Full Stack Developer
                </p>
              </div>
            </div>
          </div>
        </section>
        <About />
        <Project />
        <Skills />
        <Resume />
      </body>
    </div>
  );
}
